# Generated by Django 3.1.5 on 2021-01-06 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'virtual_domains',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('quota', models.BigIntegerField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='virtual.domain')),
            ],
            options={
                'db_table': 'virtual_users',
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=256)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='virtual.domain')),
            ],
            options={
                'db_table': 'virtual_aliases',
            },
        ),
    ]
