# Generated by Django 3.0.5 on 2020-04-10 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('quota', models.BigIntegerField()),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual.Domains')),
            ],
        ),
        migrations.CreateModel(
            name='Aliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual.Domains')),
            ],
        ),
    ]
