# Generated by Django 3.1.2 on 2020-11-01 23:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid domain name', regex='^[a-zA-Z0-9-]*\\.[a-z]*$')])),
            ],
            options={
                'db_table': 'virtual_domains',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, default=None, max_length=100)),
                ('quota', models.PositiveBigIntegerField(default=1)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual.domain')),
            ],
            options={
                'db_table': 'virtual_users',
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual.domain')),
            ],
            options={
                'db_table': 'virtual_aliases',
            },
        ),
    ]
