# Generated by Django 3.0.5 on 2020-04-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aliases',
            new_name='Alias',
        ),
        migrations.RenameModel(
            old_name='Domains',
            new_name='Domain',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='alias',
            table='virtual_aliases',
        ),
        migrations.AlterModelTable(
            name='domain',
            table='virtual_domains',
        ),
        migrations.AlterModelTable(
            name='user',
            table='virtual_users',
        ),
    ]
