# Generated by Django 3.1.4 on 2021-01-06 01:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='destination',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alias',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual.domain'),
        ),
        migrations.AlterField(
            model_name='alias',
            name='source',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid domain name', regex='^[a-zA-Z0-9-]*\\.[a-z]*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual.domain'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='quota',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
