# Generated by Django 3.0.5 on 2020-04-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0002_auto_20200410_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alias',
            old_name='domain_id',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='domain_id',
            new_name='domain',
        ),
    ]
