# Generated by Django 3.0.5 on 2020-04-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0003_auto_20200410_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.URLField(max_length=50, unique=True),
        ),
    ]
