# Generated by Django 3.0.5 on 2020-04-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0004_auto_20200411_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
