# Generated by Django 3.0.6 on 2020-05-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0005_auto_20200411_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quota',
            field=models.BigIntegerField(default=0),
        ),
    ]
