# Generated by Django 3.0.6 on 2020-05-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0006_auto_20200523_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
