# Generated by Django 3.0.6 on 2020-05-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0008_auto_20200523_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
