# Generated by Django 3.0.6 on 2020-05-24 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0010_auto_20200524_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.TextField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid domain name', regex='^[a-zA-Z0-9-]*\\.[a-z]*$')]),
        ),
    ]
