# Generated by Django 3.1.1 on 2020-09-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0011_auto_20200524_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quota',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
