# Generated by Django 3.1.2 on 2020-10-17 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0012_auto_20200914_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid domain name', regex='^[a-zA-Z0-9-]*\\.[a-z]*$')]),
        ),
    ]
