# Generated by Django 3.1.2 on 2020-10-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0013_auto_20201017_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='used_quota',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
