# Generated by Django 3.1.2 on 2020-11-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0014_user_used_quota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='used_quota',
        ),
    ]
