# Generated by Django 3.2.9 on 2021-12-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
