# Generated by Django 3.2.9 on 2021-12-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_users', '0002_company_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
