# Generated by Django 3.0.6 on 2020-05-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_users', '0002_auto_20200525_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainadmin',
            name='company',
        ),
        migrations.AddField(
            model_name='domainadmin',
            name='company',
            field=models.ManyToManyField(to='sys_users.Company'),
        ),
    ]
