# Generated by Django 3.1.2 on 2020-10-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_users', '0003_auto_20200525_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
