# Generated by Django 3.1.2 on 2020-10-25 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_users', '0004_auto_20201017_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid ID number it must be only numbers', regex='^[0-9]$')]),
        ),
    ]
