# Generated by Django 3.1.2 on 2020-11-01 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_users', '0005_auto_20201025_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid ID number it must be only numbers', regex='^[0-9]*$')]),
        ),
    ]
